### PR TITLE
fix: Writing style Guide typos

### PR DESCRIPTION
**Pull request by ghost**
# Description
Fixes typo within file

## Type of change
- [x] Documentation (update or new)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have requested a review from ... on the Pull Request

### CODE REVIEW

**Comment by ghost** [comment]
@tancnle I find it interesting that Vale does not provide a "suggestion" or "warning" for this file as it contains words explicitly stated to flag
Am I missing something?

**Comment by tancnle** [comment]
> @tancnle I find it interesting that Vale does not provide a "suggestion" or "warning" for this file as it contains words explicitly stated to flag Am I missing something?

Interesting. Which words in particular? I can see there are some typos. However, Vale is not a spell-checker per se. It does not come with a dictionary.

**Comment by ghost** [comment]
> Which words in particular? 

Almost every word that has a suggestion: "blacklist" "whitelist" "master" "slave" for example.
They are all in tables so I wonder if that makes a difference, but I would assume not.

**Comment by tancnle** [comment]
> Almost every word that has a suggestion: "blacklist" "whitelist" "master" "slave" for example. They are all in tables so I wonder if that makes a difference, but I would assume not.

Gotcha. Vale does pick them up but reports them as warnings. Hence they don't fail the CI checks. The VSCode integration should still show them though 🤔 .

Screen Shot 2022-05-17 at 9 29 42 pm

**Review by tancnle — APPROVED** [review]
Great eyes for details @talzid. Look bonza to me 🚀 :shipit:

**Pull request merged**
