### PR TITLE
Add prose linting to CI

### PR DESCRIPTION
**Pull request by tancnle**
# Description

- Fix all prose linting issues
- Add prose linting to CI

```shell
npm run prose:check

# Before
53 errors, 0 warnings, and 0 suggestions found.

# After
0 errors, 0 warnings, and 0 suggestions found.
```

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (update or new)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by tancnle** [comment]
👋🏼 @RayGuo-ergou would you kindly help me to validate the Vale integration on Windows 🙏🏼 ? I have added the instructions [here](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#install-linters) and would like to make sure the process is working for Windows users. If you have any questions, please sing out.

**Comment by RayGuo-ergou** [comment]
> 👋🏼 @RayGuo-ergou would you kindly help me to validate the Vale integration on Windows 🙏🏼 ? I have added the instructions [here](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#install-linters) and would like to make sure the process is working for Windows users. If you have any questions, please sing out.

Hi @tancnle I used Ubuntu 22.04 LTS from wsl2 in windows, and it's running okay. Here's the outputs.

<details>
  <summary>npm run format</summary>
> format

\> prettier --write "**/*.md"

.github/pull_request_template.md 36ms
CONTRIBUTING.md 37ms
docs/communication/fearless-feedback.md 58ms
docs/communication/index.md 7ms
docs/communication/professional-communication.md 14ms
docs/communication/scenarios.md 5ms
docs/company/charter.md 16ms
docs/company/reports/t1-2022/company-report-v1.md 153ms
docs/company/reports/t1-2022/company-report-v2.md 158ms
docs/company/roles.md 5ms
docs/data/data-strategy.md 19ms
docs/data/index.md 2ms
docs/data/project-metrics-template.md 7ms
docs/leadership/epic-example.md 10ms
docs/leadership/epic-template.md 2ms
docs/leadership/meeting-template.md 5ms
docs/leadership/meetings.md 6ms
docs/learning/training/changing-git-fork-location.md 8ms
docs/learning/training/configuring-jenkins.md 7ms
docs/learning/training/developing-with-wsl2.md 13ms
docs/learning/training/distinction-high-distinction-workshop.md 17ms
docs/learning/training/index.md 3ms
docs/learning/training/markdown-guide.md 11ms
docs/learning/training/trello-guide.md 51ms
docs/learning/training/writing-documentation.md 20ms
docs/learning/useful-resources/agile-software-development-teams.md 22ms
docs/learning/useful-resources/designing-and-running-experiment.md 84ms
docs/learning/useful-resources/effective-standup.md 8ms
docs/learning/useful-resources/effective-team-client-communication.md 17ms
docs/learning/useful-resources/index.md 3ms
docs/learning/useful-resources/team-and-individual-retrospectives.md 16ms
docs/marketing/pitch.md 6ms
docs/marketing/recruitment-ad.md 6ms
docs/peopleops/onboarding/onboarding-process.md 15ms
docs/processes/documentation/index.md 8ms
docs/processes/documentation/writing-style-guide.md 42ms
docs/processes/quality-assurance/git-contribution-guide.md 32ms
docs/processes/quality-assurance/quality-assurance-overview.md 6ms
docs/processes/quality-assurance/templates/bug-report-template.md 4ms
docs/processes/quality-assurance/templates/pr-template.md 5ms
docs/processes/quality-assurance/templates/srs-template.md 3ms
docs/processes/quality-assurance/templates/test-plan-template.md 2ms
docs/processes/quality-assurance/templates/test-strategy-template.md 7ms
docs/processes/quality-assurance/testing-and-dev.md 47ms
docs/products/dreambig/dreambig.md 5ms
docs/products/ontrack/ontrack.md 6ms
docs/products/ontrack/project-epics/documentation-epic.md 6ms
docs/products/splashkit/splashkit.md 16ms
docs/projects/t1-2022/teams.md 14ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-announcements/week2.md 9ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-announcements/week3.md 9ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-announcements/week4.md 6ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-announcements/week5.md 13ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-announcements/week6.md 11ms
docs/projects/t1-2022/thoth-tech-leadership/weekly-todos/week5.md 12ms
README.md 12ms
</details>

<details>
  <summary>npm run lint</summary>
> lint

\> npm run format:check && npm run prose:check
\> format:check
\> prettier --check "**/*.md"

Checking formatting...
All matched files use Prettier code style!

\> prose:check
\> vale --minAlertLevel error --output=docs/.vale/vale.tmpl docs

0 errors, 0 warnings, and 0 suggestions found.
</details>

<details>
  <summary>npm run format:check</summary>
> format:check

\> prettier --check "**/*.md"

Checking formatting...
All matched files use Prettier code style!
</details>

<details>
  <summary>npm run prose:check</summary>
> prose:check

\> vale --minAlertLevel error --output=docs/.vale/vale.tmpl docs

0 errors, 0 warnings, and 0 suggestions found.
</details>

**Comment by RayGuo-ergou** [comment]
BTW I think we can add a section about how to install `vale` for linux so the linux user does not need to go to homebrew or vale document.

like 
```bash
wget https://github.com/errata-ai/vale/releases/download/v2.15.4/vale_2.15.4_Linux_64-bit.tar.gz
mkdir bin && tar -xvzf vale_2.15.4_Linux_64-bit.tar.gz -C bin
export PATH=./bin:"$PATH"
```

or 

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/$USER/.zprofile
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
brew install vale
```

What do you think?

**Comment by ghost** [comment]
> BTW I think we can add a section about how to install `vale` for linux so the linux user does not need to go to homebrew or vale document.
> 
> like
> 
> ```shell
> wget https://github.com/errata-ai/vale/releases/download/v2.15.4/vale_2.15.4_Linux_64-bit.tar.gz
> mkdir bin && tar -xvzf vale_2.15.4_Linux_64-bit.tar.gz -C bin
> export PATH=./bin:"$PATH"
> ```
> 
> or
> 
> ```shell
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
> echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /home/$USER/.zprofile
> eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
> brew install vale
> ```
>

I don't know if I am installing this wrong, but I can't seem to get vale to download without creating files in the handbook, is this correct? I am also using WSL and ubuntu 

I tried to install using snap but it just errored out.

Secondly, is there a way to run vale without running prettier? This is not really important, but more for consistency, as you can run the formatter by itself? (However as writing this, it makes sense as prettier is useful for more than just docs) Maybe I answered my own question...

**Comment by RayGuo-ergou** [comment]
> I don't know if I am installing this wrong, but I can't seem to get vale to download without creating files in the handbook, is this correct? I am also using WSL and ubuntu
> 
> I tried to install using snap but it just errored out.
> 
> Secondly, is there a way to run vale without running prettier? This is not really important, but more for consistency, as you can run the formatter by itself? (However as writing this, it makes sense as prettier is useful for more than just docs) Maybe I answered my own question...

Hi @talzid by saying "without creating files in the handbook" do you mean download the release file from the github? If in that case, you do not need to download the file in this repo's folder as long as you added the `bin` into `PATH` (you can also put the file in `/bin` so you dont need to add `PATH`). For the snap one I think the channel edge might be the reason but I haven't tried to download `vale` from snap so I will do some test first.

**Comment by tancnle** [comment]
Thanks for the prompt response @RayGuo-ergou. Really appreciated.

> BTW I think we can add a section about how to install vale for linux so the linux user does not need to go to homebrew or vale document.

Good point. However, I would avoid duplicating the installation instructions from the canonical source.

- Increase maintenance effort
- Risk of being stale and becoming inaccurate

From the documentation standpoint, having a single source of truth (SSOT) is an important principle and I would love to incorporate it into Thoth Tech guidelines in the next iteration.

**Comment by tancnle** [comment]
@talzid 

> Secondly, is there a way to run vale without running prettier? 

Yep, we can. I have documented the [command](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#lint-checks) in the `CONTRIBUTING.md` doc. TL;DR you can run

```shell
npm run prose:check
```

**Comment by RayGuo-ergou** [comment]
> I don't know if I am installing this wrong, but I can't seem to get vale to download without creating files in the handbook, is this correct? I am also using WSL and ubuntu
> 
> I tried to install using snap but it just errored out.
> 
> Secondly, is there a way to run vale without running prettier? This is not really important, but more for consistency, as you can run the formatter by itself? (However as writing this, it makes sense as prettier is useful for more than just docs) Maybe I answered my own question...

I remembered the reason why you have error with snapd I faced it when I wanted to install `microk8s` for WSL2 Ubuntu due to not have systemd, check this [github issue](https://github.com/microsoft/WSL/issues/5126). You can install systemd from a [repo](https://github.com/DamionGans/ubuntu-wsl2-systemd-script) but you probably will face some glitch after that e.g. the VS code Terminal would always open in home directory instead of ` {workingspace}`. So I think the best way to install `vale` would be either github release or homebrew.

**Comment by RayGuo-ergou** [comment]
> Good point. However, I would avoid duplicating the installation instructions from the canonical source.
> 
> * Increase maintenance effort
> * Risk of being stale and becoming inaccurate
> 
> From the documentation standpoint, having a single source of truth (SSOT) is an important principle and I would love to incorporate it into Thoth Tech guidelines in the next iteration.

Yeah make sence.

**Comment by ghost** [comment]
> Hi @talzid by saying "without creating files in the handbook" do you mean download the release file from the github? If in that case, you do not need to download the file in this repo's folder as long as you added the `bin` into `PATH` (you can also put the file in `/bin` so you dont need to add `PATH`). For the snap one I think the channel edge might be the reason but I haven't tried to download `vale` from snap so I will do some test first.

You are absolutely correct, I just couldn't read the errors properly. Just needed to add a sudo to get it working in the bin directory.

> Yep, we can. I have documented the [command](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#lint-checks) in the `CONTRIBUTING.md` doc. TL;DR you can run
> 
> ```shell
> npm run prose:check
> ```
This makes sense now! I had it in my head that it would auto change like the formatter, but it is suggestions, errors, and warnings 👍

**Review by ghost — APPROVED** [review]
Thank you @tancnle for this masterpiece and taking the time to explain it all.
I am very much looking forward to this and hope to have it added to the docs repo as well.

**Comment by tancnle** [comment]
@talzid 

> I had it in my head that it would auto change like the formatter, but it is suggestions, errors, and warnings 👍

The `prose:check` command only reports error [type](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#vale-result-types). For future PRs, if there are errors, the build will fail and merge will be stop until they are all addressed.

As good practice, we should try to address `warning` and `suggestion`. I believe this can be observed via the [editor integration](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#configure-editors). Do you or @RayGuo-ergou have a chance to test it out?

**Comment by RayGuo-ergou** [comment]
> As good practice, we should try to address `warning` and `suggestion`. I believe this can be observed via the [editor integration](https://github.com/thoth-tech/handbook/blob/main/CONTRIBUTING.md#configure-editors). Do you or @RayGuo-ergou have a chance to test it out?

image

It has the issues report in `Problems` section. But I don't think it will auto change.🤔

**Comment by tancnle** [comment]
Thanks @RayGuo-ergou 

> It has the issues report in `Problems` section. But I don't think it will auto change.🤔

The leading icons seem to indicate they are warnings, not errors. `vale` only highlights issues, it does not provide format capability.

**Comment by ghost** [comment]
Regarding the issues identified in the company v1 report: I will go and edit it later today to save anyone from the spam going forward. In the meantime if we are all happy, I think this is ready to merge ?

**Pull request merged**
