### PR TITLE
ADD: Leadership Diagrams and planning evidence to handbook

### PR DESCRIPTION
**Pull request by ginge270**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Nice work!
The leadership structure requires updating
Ethan as Delivery Lead

**Comment by tancnle** [comment]
@ginge270 There seems to be a lot of changes that are already in the `main` branch 🤔 Can you merge/rebase from the `main` branch to reduce the changeset in this PR 🙏🏼 ?

**Review by ghost — APPROVED** [review]
First iteration of leadership 
Looks good!

**Review by tancnle — APPROVED** [review]
Thanks, @ginge270. The PR looks good to me 🚢

**Pull request merged**
